### ISSUE TITLE
BUG: Graph Optimization models parameter renaming error

### ISSUE THREAD

**Issue by caksland** [renkert2/GraphTools#61]
The Graph model parameters names are provided by the user e.g. Kv__Motor. 
However, when the graph model is converted to a general model, the SymVars parameter property is named theta. The SymVar.theta.Sym values are then renamed to have the Param Sym value (e.g. theta1 is renamed to Kv_motor).
This is an issue in Dymos, because the code is looking for variables name thetaX, not Kv_motor... We should probably fix this...

**Comment by renkert2** [comment]
We're still treating everything as scalar values in Dymos right?  I think right now we're adding variables/parameters into Dymos using the element names (i.e. "x1", "u2", "Kv_Motor") instead of the variable names ("x", "u", "theta").  Does the variable name theta ever get passed into Dymos?  To my knowledge it currently has no idea what "theta" is, so it would never try to look for "thetaX" unless we named the elements in the theta vector "thetaX".  But I could be forgetting something.

**Comment by caksland** [comment]
See ->OpenMDAO->TESTS->StaticVarsBug for a demonstration. If you look at the n2, you'll see that the defined parameters are not static.
